// Code generated by protoc-gen-defaults. DO NOT EDIT.

package rightsval

import "fmt"
import "context"
import "google.golang.org/grpc/codes"
import "google.golang.org/grpc/status"
import "go.uber.org/fx"
import "go.appointy.com/google/pb/rights"
import "go.appointy.com/google/userinfo"


import "github.com/golang/protobuf/ptypes/empty"

import "github.com/ayushbpl10/protoc-gen-rights/example/example/pb"






    type RightsUsersServer struct {
        pb.UsersServer
        rightsCli rights.RightValidatorsClient
    }

    func init() {
        options = append(options, fx.Provide(NewRightsUsersClient))
    }

    type RightsUsersClientResult struct {
        fx.Out
        UsersClient pb.AcceptancesClient `name:"r"`
    }

    func NewRightsUsersClient(c rights.RightValidatorsClient, s pb.UsersServer) RightsUsersClientResult {
        return RightsUsersClientResult{ UsersClient: pb.NewLocalUsersClient(NewRightsUsersServer(c, s))}
    }
    func NewRightsUsersServer(c rights.RightValidatorsClient, s pb.UsersServer) pb.UsersServer {
        return &RightsUsersServer{
            s,
            c,
        }
    }

    
        func (s *RightsUsersServer) AddUser(ctx context.Context, rightsvar *pb.User) (*empty.Empty, error) {



            res, err := s.rightsCli.IsValid(ctx, &rights.IsValidReq{
                ResourcePath: []string{ fmt.Sprintf("/users/%s/cards/",  rightsvar.GetUserId(),  ),fmt.Sprintf("/users/%s/cards/user",  rightsvar.GetUserId(),  ), },
                Value:        2,
                Choice:       0,
                UserId:       userinfo.FromContext(ctx).Id,
            })
            if err != nil {
                return nil, err
            }




            if !res.IsValid {
                return nil, status.Errorf(codes.PermissionDenied, res.Reason)
            }
            return s.UsersServer.AddUser(ctx, rightsvar)
        }

    
        func (s *RightsUsersServer) GetUser(ctx context.Context, rightsvar *pb.GetUserReq) (*pb.User, error) {



            res, err := s.rightsCli.IsValid(ctx, &rights.IsValidReq{
                ResourcePath: []string{ fmt.Sprintf("/users/{user_id}/cards/%s",  rightsvar.GetUserId(),  rightsvar.GetTentId().GetTent(),  ),fmt.Sprintf("/users/{user_id}/cards/%s/ex",  rightsvar.GetUserId(),  rightsvar.GetTentId().GetTent(),  ), },
                Value:        1,
                Choice:       1,
                UserId:       userinfo.FromContext(ctx).Id,
            })
            if err != nil {
                return nil, err
            }




            if !res.IsValid {
                return nil, status.Errorf(codes.PermissionDenied, res.Reason)
            }
            return s.UsersServer.GetUser(ctx, rightsvar)
        }

    


