// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/example.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
	_ "rights"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//    string first_name = 2  [(zap.redact) = true];
	//    string last_name = 3  [(zap.redact) = true];
	//    int64 employee_number = 4 [(zap.redact) = true];
	//    string physical_desk = 6;
	//    ServiceMsg service =8;
	//
	Blocked              []string             `protobuf:"bytes,2,rep,name=blocked,proto3" json:"blocked,omitempty"`
	Extra                map[string]string    `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HireDate             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=hire_date,json=hireDate,proto3" json:"hire_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetBlocked() []string {
	if m != nil {
		return m.Blocked
	}
	return nil
}

func (m *User) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *User) GetHireDate() *timestamp.Timestamp {
	if m != nil {
		return m.HireDate
	}
	return nil
}

//message ServiceMsg {
//    string id = 1;
//    string name = 2;
//}
type GetUserReq struct {
	UserId               string        `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TentId               *Demo         `protobuf:"bytes,2,opt,name=tent_id,json=tentId,proto3" json:"tent_id,omitempty"`
	UserEmail            []*UserEmails `protobuf:"bytes,3,rep,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserReq) GetTentId() *Demo {
	if m != nil {
		return m.TentId
	}
	return nil
}

func (m *GetUserReq) GetUserEmail() []*UserEmails {
	if m != nil {
		return m.UserEmail
	}
	return nil
}

type UserEmails struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Checks               []*Check `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEmails) Reset()         { *m = UserEmails{} }
func (m *UserEmails) String() string { return proto.CompactTextString(m) }
func (*UserEmails) ProtoMessage()    {}
func (*UserEmails) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2}
}

func (m *UserEmails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEmails.Unmarshal(m, b)
}
func (m *UserEmails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEmails.Marshal(b, m, deterministic)
}
func (m *UserEmails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEmails.Merge(m, src)
}
func (m *UserEmails) XXX_Size() int {
	return xxx_messageInfo_UserEmails.Size(m)
}
func (m *UserEmails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEmails.DiscardUnknown(m)
}

var xxx_messageInfo_UserEmails proto.InternalMessageInfo

func (m *UserEmails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserEmails) GetChecks() []*Check {
	if m != nil {
		return m.Checks
	}
	return nil
}

type Check struct {
	Check                string   `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Check) Reset()         { *m = Check{} }
func (m *Check) String() string { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()    {}
func (*Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{3}
}

func (m *Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check.Unmarshal(m, b)
}
func (m *Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check.Marshal(b, m, deterministic)
}
func (m *Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check.Merge(m, src)
}
func (m *Check) XXX_Size() int {
	return xxx_messageInfo_Check.Size(m)
}
func (m *Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Check proto.InternalMessageInfo

func (m *Check) GetCheck() string {
	if m != nil {
		return m.Check
	}
	return ""
}

type Demo struct {
	Tent                 string   `protobuf:"bytes,1,opt,name=tent,proto3" json:"tent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Demo) Reset()         { *m = Demo{} }
func (m *Demo) String() string { return proto.CompactTextString(m) }
func (*Demo) ProtoMessage()    {}
func (*Demo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{4}
}

func (m *Demo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demo.Unmarshal(m, b)
}
func (m *Demo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demo.Marshal(b, m, deterministic)
}
func (m *Demo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demo.Merge(m, src)
}
func (m *Demo) XXX_Size() int {
	return xxx_messageInfo_Demo.Size(m)
}
func (m *Demo) XXX_DiscardUnknown() {
	xxx_messageInfo_Demo.DiscardUnknown(m)
}

var xxx_messageInfo_Demo proto.InternalMessageInfo

func (m *Demo) GetTent() string {
	if m != nil {
		return m.Tent
	}
	return ""
}

type UpdateUserReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserReq) Reset()         { *m = UpdateUserReq{} }
func (m *UpdateUserReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReq) ProtoMessage()    {}
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{5}
}

func (m *UpdateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReq.Unmarshal(m, b)
}
func (m *UpdateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReq.Merge(m, src)
}
func (m *UpdateUserReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReq.Size(m)
}
func (m *UpdateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReq proto.InternalMessageInfo

func (m *UpdateUserReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "example.User")
	proto.RegisterMapType((map[string]string)(nil), "example.User.ExtraEntry")
	proto.RegisterType((*GetUserReq)(nil), "example.GetUserReq")
	proto.RegisterType((*UserEmails)(nil), "example.UserEmails")
	proto.RegisterType((*Check)(nil), "example.Check")
	proto.RegisterType((*Demo)(nil), "example.Demo")
	proto.RegisterType((*UpdateUserReq)(nil), "example.UpdateUserReq")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x1d, 0x27, 0x26, 0x13, 0x52, 0xa1, 0x2d, 0xb4, 0x96, 0x01, 0x35, 0xf2, 0xa1, 0xca,
	0x69, 0x2d, 0x85, 0x43, 0x2b, 0xb8, 0xf0, 0x93, 0x08, 0x95, 0xa3, 0x45, 0x2f, 0x1c, 0xa8, 0x9c,
	0xec, 0x90, 0x58, 0x89, 0x6b, 0x63, 0x6f, 0x4a, 0xa2, 0xc8, 0x07, 0xde, 0x80, 0x0b, 0x97, 0x3c,
	0x0e, 0x12, 0x4f, 0xc0, 0x7b, 0xe4, 0x19, 0xd0, 0xfe, 0x38, 0x26, 0x8d, 0x8a, 0x7a, 0xc9, 0xec,
	0xcc, 0x37, 0x9e, 0xfd, 0xbe, 0x6f, 0x56, 0x81, 0x27, 0xb8, 0x08, 0xe3, 0x74, 0x86, 0xbe, 0x8e,
	0x34, 0xcd, 0x12, 0x9e, 0x10, 0x5b, 0xa7, 0xee, 0xc9, 0x38, 0x49, 0xc6, 0x33, 0xf4, 0x65, 0x79,
	0x38, 0xff, 0xe2, 0xf3, 0x28, 0xc6, 0x9c, 0x87, 0x71, 0xaa, 0x3a, 0xdd, 0xa7, 0xb7, 0x1b, 0x30,
	0x4e, 0xf9, 0x52, 0x83, 0x87, 0x59, 0x34, 0x9e, 0xf0, 0xdc, 0x57, 0x41, 0x15, 0xbd, 0x3f, 0x06,
	0x58, 0x97, 0x39, 0x66, 0xe4, 0x00, 0xcc, 0x88, 0x39, 0x46, 0xc7, 0xe8, 0x36, 0x03, 0x33, 0x62,
	0xc4, 0x01, 0x7b, 0x38, 0x4b, 0x46, 0x53, 0x64, 0x8e, 0xd9, 0xa9, 0x75, 0x9b, 0x41, 0x99, 0x12,
	0x0a, 0x75, 0x5c, 0xf0, 0x2c, 0x74, 0x6a, 0x9d, 0x5a, 0xb7, 0xd5, 0x73, 0x68, 0xc9, 0x56, 0xcc,
	0xa1, 0x03, 0x01, 0x0d, 0xae, 0x79, 0xb6, 0x0c, 0x54, 0x1b, 0x39, 0x83, 0xe6, 0x24, 0xca, 0xf0,
	0x8a, 0x85, 0x1c, 0x1d, 0xab, 0x63, 0x74, 0x5b, 0x3d, 0x97, 0x2a, 0xa2, 0xb4, 0x24, 0x4a, 0x3f,
	0x96, 0x4a, 0x82, 0x07, 0xa2, 0xb9, 0x1f, 0x72, 0x74, 0xcf, 0x01, 0xaa, 0x69, 0xe4, 0x11, 0xd4,
	0xa6, 0xb8, 0xd4, 0x0c, 0xc5, 0x91, 0x3c, 0x86, 0xfa, 0x4d, 0x38, 0x9b, 0xa3, 0x63, 0xca, 0x9a,
	0x4a, 0x5e, 0x9a, 0xe7, 0x86, 0xf7, 0xdd, 0x00, 0x78, 0x8f, 0x5c, 0x10, 0x0a, 0xf0, 0x2b, 0x39,
	0x06, 0x7b, 0x9e, 0x63, 0x76, 0xb5, 0x15, 0xd8, 0x10, 0xe9, 0x05, 0x23, 0xa7, 0x60, 0x73, 0xbc,
	0xe6, 0x02, 0x30, 0x25, 0xb1, 0xf6, 0x56, 0x4c, 0x1f, 0xe3, 0x24, 0x68, 0x08, 0xf4, 0x82, 0x91,
	0x1e, 0x80, 0x1c, 0x80, 0x71, 0x18, 0xcd, 0xb4, 0xee, 0xc3, 0x1d, 0xdd, 0x03, 0x81, 0xe4, 0x41,
	0x73, 0x5e, 0x9e, 0xbd, 0x0f, 0x00, 0x15, 0x20, 0xb8, 0xaa, 0x8f, 0x15, 0x01, 0x95, 0x90, 0x53,
	0x68, 0x8c, 0x26, 0x38, 0x9a, 0xe6, 0xd2, 0xe3, 0x56, 0xef, 0x60, 0x3b, 0xf3, 0x9d, 0x28, 0x07,
	0x1a, 0xf5, 0x9e, 0x43, 0x5d, 0x16, 0xc4, 0x18, 0x59, 0x2a, 0xc7, 0xc8, 0xc4, 0x73, 0xc1, 0x12,
	0x74, 0x09, 0x01, 0x4b, 0x10, 0xd6, 0xa0, 0x3c, 0x7b, 0x27, 0xd0, 0xbe, 0x4c, 0x85, 0xf5, 0xa5,
	0x19, 0xb7, 0x16, 0xdd, 0xfb, 0x55, 0x83, 0xba, 0xc0, 0x72, 0x72, 0x03, 0xf6, 0x1b, 0xc6, 0xe4,
	0x6b, 0x68, 0xef, 0x88, 0x73, 0x8f, 0xf6, 0xf6, 0x35, 0x10, 0x0f, 0xcb, 0xeb, 0xaf, 0x37, 0xd6,
	0x6b, 0xe8, 0xf8, 0x42, 0x75, 0xee, 0xaf, 0x22, 0x56, 0xf8, 0xa3, 0x30, 0x63, 0x39, 0xcd, 0x30,
	0x64, 0xfe, 0x4a, 0xbf, 0x98, 0x02, 0x9e, 0xed, 0x75, 0xc8, 0x02, 0xfd, 0x96, 0x45, 0x1c, 0xc9,
	0x6f, 0x03, 0x6c, 0xbd, 0x2d, 0x52, 0xb9, 0x5a, 0xed, 0xcf, 0xdd, 0x65, 0xe3, 0xfd, 0x34, 0xd6,
	0x1b, 0xeb, 0x87, 0x01, 0x9f, 0xfd, 0x55, 0xb5, 0x15, 0x2a, 0x7f, 0x8b, 0xf2, 0x22, 0xbd, 0xef,
	0xf2, 0xb6, 0x95, 0x5e, 0x33, 0x15, 0xb1, 0xf0, 0x65, 0xef, 0xfe, 0xd7, 0x54, 0xd9, 0xad, 0x42,
	0x01, 0xf4, 0x9e, 0xc3, 0x16, 0x5a, 0xc7, 0x12, 0xa0, 0xb2, 0x9a, 0x1c, 0x55, 0xa4, 0xff, 0xf5,
	0xff, 0x4e, 0x2f, 0x5f, 0xad, 0x37, 0xd6, 0x19, 0x1c, 0xdf, 0xe1, 0xe5, 0xff, 0x2d, 0x7c, 0xfb,
	0xf0, 0x13, 0x94, 0xff, 0x1d, 0xe9, 0x70, 0xd8, 0x90, 0xa3, 0x5f, 0xfc, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xeb, 0x35, 0x20, 0x5c, 0x50, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/example.Users/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/example.Users/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/example.Users/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	AddUser(context.Context, *User) (*empty.Empty, error)
	GetUser(context.Context, *GetUserReq) (*User, error)
	UpdateUser(context.Context, *UpdateUserReq) (*empty.Empty, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Users/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Users/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Users/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _Users_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Users_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Users_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/example.proto",
}
