// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rights/rights.proto

package rightspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChoiceOfRight int32

const (
	ChoiceOfRight_AND ChoiceOfRight = 0
	ChoiceOfRight_OR  ChoiceOfRight = 1
)

var ChoiceOfRight_name = map[int32]string{
	0: "AND",
	1: "OR",
}

var ChoiceOfRight_value = map[string]int32{
	"AND": 0,
	"OR":  1,
}

func (x ChoiceOfRight) String() string {
	return proto.EnumName(ChoiceOfRight_name, int32(x))
}

func (ChoiceOfRight) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6ae2826152cb355, []int{0}
}

type MyRights struct {
	Resource             []string      `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	Right                int32         `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`
	Choice               ChoiceOfRight `protobuf:"varint,3,opt,name=choice,proto3,enum=rights.ChoiceOfRight" json:"choice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MyRights) Reset()         { *m = MyRights{} }
func (m *MyRights) String() string { return proto.CompactTextString(m) }
func (*MyRights) ProtoMessage()    {}
func (*MyRights) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae2826152cb355, []int{0}
}

func (m *MyRights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyRights.Unmarshal(m, b)
}
func (m *MyRights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyRights.Marshal(b, m, deterministic)
}
func (m *MyRights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyRights.Merge(m, src)
}
func (m *MyRights) XXX_Size() int {
	return xxx_messageInfo_MyRights.Size(m)
}
func (m *MyRights) XXX_DiscardUnknown() {
	xxx_messageInfo_MyRights.DiscardUnknown(m)
}

var xxx_messageInfo_MyRights proto.InternalMessageInfo

func (m *MyRights) GetResource() []string {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *MyRights) GetRight() int32 {
	if m != nil {
		return m.Right
	}
	return 0
}

func (m *MyRights) GetChoice() ChoiceOfRight {
	if m != nil {
		return m.Choice
	}
	return ChoiceOfRight_AND
}

var E_Validator = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MyRights)(nil),
	Field:         9955,
	Name:          "rights.validator",
	Tag:           "bytes,9955,opt,name=validator",
	Filename:      "rights/rights.proto",
}

func init() {
	proto.RegisterEnum("rights.ChoiceOfRight", ChoiceOfRight_name, ChoiceOfRight_value)
	proto.RegisterType((*MyRights)(nil), "rights.MyRights")
	proto.RegisterExtension(E_Validator)
}

func init() { proto.RegisterFile("rights/rights.proto", fileDescriptor_c6ae2826152cb355) }

var fileDescriptor_c6ae2826152cb355 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xc7, 0xcd, 0xca, 0x6a, 0xf7, 0x88, 0x52, 0xa2, 0x42, 0xd9, 0x41, 0x82, 0xa7, 0x22, 0x98,
	0xc2, 0xbc, 0x79, 0xf3, 0xe5, 0x5a, 0x03, 0x39, 0x7a, 0x5b, 0xd3, 0xac, 0x0d, 0x0e, 0x9f, 0x90,
	0x64, 0x82, 0x9f, 0xd7, 0x2f, 0x22, 0x24, 0xad, 0xb2, 0x53, 0xf8, 0xbf, 0xf0, 0xcb, 0xff, 0x81,
	0x4b, 0x67, 0x86, 0x31, 0xf8, 0x26, 0x3d, 0xdc, 0x3a, 0x0c, 0x48, 0xf3, 0xa4, 0xd6, 0x6c, 0x40,
	0x1c, 0xf6, 0xba, 0x89, 0x6e, 0x77, 0xd8, 0x35, 0xbd, 0xf6, 0xca, 0x19, 0x1b, 0xd0, 0xa5, 0xe6,
	0xed, 0x07, 0x14, 0xed, 0xb7, 0x8c, 0x6d, 0xba, 0x86, 0xc2, 0x69, 0x8f, 0x07, 0xa7, 0x74, 0x45,
	0x58, 0x56, 0xaf, 0xe4, 0x9f, 0xa6, 0x57, 0xb0, 0x8c, 0xcc, 0x6a, 0xc1, 0x48, 0xbd, 0x94, 0x49,
	0xd0, 0x7b, 0xc8, 0xd5, 0x88, 0x46, 0xe9, 0x2a, 0x63, 0xa4, 0xbe, 0xd8, 0x5c, 0xf3, 0x69, 0xc6,
	0x4b, 0x74, 0xc5, 0x2e, 0x92, 0xe5, 0x54, 0xba, 0x63, 0x70, 0x7e, 0x14, 0xd0, 0x53, 0xc8, 0x9e,
	0xde, 0x5e, 0xcb, 0x13, 0x9a, 0xc3, 0x42, 0xc8, 0x92, 0x3c, 0x0a, 0x58, 0x7d, 0x6d, 0xf7, 0xa6,
	0xdf, 0x06, 0x74, 0xf4, 0x86, 0xa7, 0xf9, 0x7c, 0x9e, 0xcf, 0x5b, 0x1d, 0x46, 0xec, 0x85, 0x0d,
	0x06, 0x3f, 0x7d, 0xf5, 0xd3, 0x32, 0x52, 0x9f, 0x6d, 0xca, 0xf9, 0xd3, 0xf9, 0x10, 0xf9, 0xcf,
	0x78, 0x86, 0xf7, 0x22, 0xa5, 0xb6, 0xeb, 0xf2, 0xc8, 0x79, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x24, 0xca, 0xa4, 0xb8, 0x33, 0x01, 0x00, 0x00,
}
