// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rights/rights.proto

package rightspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MyRights struct {
	Resource             []string `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyRights) Reset()         { *m = MyRights{} }
func (m *MyRights) String() string { return proto.CompactTextString(m) }
func (*MyRights) ProtoMessage()    {}
func (*MyRights) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae2826152cb355, []int{0}
}

func (m *MyRights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyRights.Unmarshal(m, b)
}
func (m *MyRights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyRights.Marshal(b, m, deterministic)
}
func (m *MyRights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyRights.Merge(m, src)
}
func (m *MyRights) XXX_Size() int {
	return xxx_messageInfo_MyRights.Size(m)
}
func (m *MyRights) XXX_DiscardUnknown() {
	xxx_messageInfo_MyRights.DiscardUnknown(m)
}

var xxx_messageInfo_MyRights proto.InternalMessageInfo

func (m *MyRights) GetResource() []string {
	if m != nil {
		return m.Resource
	}
	return nil
}

var E_Validator = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MyRights)(nil),
	Field:         9955,
	Name:          "rights.validator",
	Tag:           "bytes,9955,opt,name=validator",
	Filename:      "rights/rights.proto",
}

func init() {
	proto.RegisterType((*MyRights)(nil), "rights.MyRights")
	proto.RegisterExtension(E_Validator)
}

func init() { proto.RegisterFile("rights/rights.proto", fileDescriptor_c6ae2826152cb355) }

var fileDescriptor_c6ae2826152cb355 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xca, 0x4c, 0xcf,
	0x28, 0x29, 0xd6, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x94,
	0x42, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x58, 0x34, 0xa9, 0x34, 0x4d, 0x3f, 0x25, 0xb5,
	0x38, 0xb9, 0x28, 0xb3, 0xa0, 0x24, 0xbf, 0x08, 0xa2, 0x52, 0x49, 0x8d, 0x8b, 0xc3, 0xb7, 0x32,
	0x08, 0xac, 0x5a, 0x48, 0x8a, 0x8b, 0xa3, 0x28, 0xb5, 0x38, 0xbf, 0xb4, 0x28, 0x39, 0x55, 0x82,
	0x51, 0x81, 0x59, 0x83, 0x33, 0x08, 0xce, 0xb7, 0xf2, 0xe7, 0xe2, 0x2c, 0x4b, 0xcc, 0xc9, 0x4c,
	0x49, 0x2c, 0xc9, 0x2f, 0x12, 0x92, 0xd3, 0x83, 0x98, 0xab, 0x07, 0x33, 0x57, 0xcf, 0x37, 0xb5,
	0x24, 0x23, 0x3f, 0xc5, 0xbf, 0xa0, 0x24, 0x33, 0x3f, 0xaf, 0x58, 0xe2, 0xb1, 0xaf, 0x02, 0xa3,
	0x06, 0xb7, 0x91, 0x80, 0x1e, 0xd4, 0x51, 0x30, 0x1b, 0x82, 0x10, 0x66, 0x38, 0x71, 0x45, 0x71,
	0x40, 0x64, 0x0b, 0x92, 0x92, 0xd8, 0xc0, 0xe6, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0x35, 0x58, 0x7f, 0xcc, 0x00, 0x00, 0x00,
}
